# Generated by Django 4.1.3 on 2022-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Name', models.CharField(max_length=40)),
                ('Faculty_Subject', models.CharField(max_length=49)),
                ('Faculty_Experience', models.IntegerField()),
                ('Faculty_Age', models.IntegerField()),
                ('Faculty_Qualification', models.CharField(max_length=48)),
                ('Faculty_Achievements', models.CharField(max_length=40)),
                ('Faculty_Email', models.EmailField(max_length=40)),
                ('Faculty_Mobile_Number', models.IntegerField()),
            ],
        ),
    ]
