# Generated by Django 4.1.3 on 2022-11-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='Faculty_Name',
            new_name='name',
        ),
    ]
