# Generated by Django 4.1.3 on 2022-11-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_faculty_name_faculty_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='Faculty_Achievements',
            new_name='Achievements',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Faculty_Age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Faculty_Email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Faculty_Experience',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Faculty_Mobile_Number',
            new_name='Mobile_Number',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Faculty_Qualification',
            new_name='Qualification',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Faculty_Subject',
            new_name='Subject',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
