# Generated by Django 4.1.3 on 2022-11-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_faculty_achievements_faculty_achievements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='Achievements',
            new_name='Faculty_Achievements',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Age',
            new_name='Faculty_Age',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Email',
            new_name='Faculty_Email',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Experience',
            new_name='Faculty_Experience',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Mobile_Number',
            new_name='Faculty_Mobile_Number',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Qualification',
            new_name='Faculty_Qualification',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Subject',
            new_name='Faculty_Subject',
        ),
    ]
